/**
 * languages.js
 * ─────────────────────────────────────────────────────────────────────────────
 * Supported Regional Language Configuration for Shilp Setu
 * Configured with standard BCP 47 language codes for TTS compatibility.
 *
 * Integration Note:
 * While Gujarati, Hindi, and Kannada will work flawlessly with TTS out of the
 * box, the browser's OS-level speech packs will dictate whether native audio plays
 * for Bodo, Dogri, Goan Konkani, Kashmiri, and Maithili. The UI text translation
 * (via the Gemini AI translation pipeline) will work perfectly for all 8 languages
 * regardless of the device's audio capabilities.
 * ─────────────────────────────────────────────────────────────────────────────
 */

export const ADDITIONAL_LANGUAGES = [
  {
    code: 'brx-IN',
    name: 'Bodo',
    nativeName: 'बड़ो',
    native: 'बड़ो',
    script: 'Devanagari',
    region: 'Assam & North-East India',
    keyChar: 'ब',
    color: '#0d9488',
  },
  {
    code: 'doi-IN',
    name: 'Dogri',
    nativeName: 'डोगरी',
    native: 'डोगरी',
    script: 'Devanagari',
    region: 'Jammu & Kashmir / Himachal',
    keyChar: 'डो',
    color: '#4f46e5',
  },
  {
    code: 'kok-IN',
    name: 'Goan Konkani',
    nativeName: 'गोवा कोंकणी',
    native: 'गोवा कोंकणी',
    script: 'Devanagari',
    region: 'Goa & Konkan Coast',
    keyChar: 'कों',
    color: '#e11d48',
  },
  {
    code: 'gu-IN',
    name: 'Gujarati',
    nativeName: 'ગુજરાતી',
    native: 'ગુજરાતી',
    script: 'Gujarati',
    region: 'Gujarat & Western India',
    keyChar: 'ગુ',
    color: '#ea580c',
  },
  {
    code: 'hi-IN',
    name: 'Hindi',
    nativeName: 'हिन्दी',
    native: 'हिन्दी',
    script: 'Devanagari',
    region: 'North & Central India',
    keyChar: 'अ',
    color: '#9c441c',
  },
  {
    code: 'kn-IN',
    name: 'Kannada',
    nativeName: 'ಕನ್ನಡ',
    native: 'ಕನ್ನಡ',
    script: 'Kannada',
    region: 'Karnataka & South India',
    keyChar: 'ಕ',
    color: '#059669',
  },
  {
    code: 'ks-IN',
    name: 'Kashmiri',
    nativeName: 'कश्मीरी',
    native: 'कश्मीरी',
    script: 'Perso-Arabic / Devanagari',
    region: 'Kashmir Valley & North India',
    keyChar: 'क',
    color: '#7c3aed',
  },
  {
    code: 'mai-IN',
    name: 'Maithili',
    nativeName: 'मैथिली',
    native: 'मैथिली',
    script: 'Devanagari / Mithilakshar',
    region: 'Mithila, Bihar & Jharkhand',
    keyChar: 'मै',
    color: '#ca8a04',
  },
];

export const SUPPORTED_LANGUAGES = [
  {
    code: 'hi',
    ttsCode: 'hi-IN',
    name: 'Hindi',
    nativeName: 'हिन्दी',
    native: 'हिंदी',
    script: 'Devanagari',
    region: 'North & Central India',
    keyChar: 'अ',
    color: '#9c441c',
  },
  {
    code: 'en',
    ttsCode: 'en-IN',
    name: 'English',
    nativeName: 'English',
    native: 'English',
    script: 'Latin',
    region: 'Pan-India / Institutional',
    keyChar: 'A',
    color: '#2e241e',
  },
  {
    code: 'bn',
    ttsCode: 'bn-IN',
    name: 'Bengali',
    nativeName: 'বাংলা',
    native: 'বাংলা',
    script: 'Bengali',
    region: 'West Bengal & East India',
    keyChar: 'অ',
    color: '#b45309',
  },
  {
    code: 'mr',
    ttsCode: 'mr-IN',
    name: 'Marathi',
    nativeName: 'मराठी',
    native: 'मराठी',
    script: 'Devanagari',
    region: 'Maharashtra & West India',
    keyChar: 'म',
    color: '#c2410c',
  },
  {
    code: 'or-IN',
    ttsCode: 'or-IN',
    name: 'Odia',
    nativeName: 'ଓଡ଼ିଆ',
    native: 'ଓଡ଼ିଆ',
    script: 'Odia',
    region: 'Odisha & East India',
    keyChar: 'ଓ',
    color: '#0284c7',
  },
  {
    code: 'pa-IN',
    ttsCode: 'pa-IN',
    name: 'Punjabi',
    nativeName: 'ਪੰਜਾਬੀ',
    native: 'ਪੰਜਾਬੀ',
    script: 'Gurmukhi',
    region: 'Punjab & North-West India',
    keyChar: 'ਪ',
    color: '#d97706',
  },
  {
    code: 'sa-IN',
    ttsCode: 'sa-IN',
    name: 'Sanskrit',
    nativeName: 'संस्कृत',
    native: 'संस्कृत',
    script: 'Devanagari',
    region: 'Pan-India Classical',
    keyChar: 'सं',
    color: '#7c3aed',
  },
  {
    code: 'sat-IN',
    ttsCode: 'sat-IN',
    name: 'Santali',
    nativeName: 'संताली',
    native: 'संताली',
    script: 'Ol Chiki / Devanagari',
    region: 'Jharkhand, Odisha & West Bengal',
    keyChar: 'सं',
    color: '#059669',
  },
  {
    code: 'sd-IN',
    ttsCode: 'sd-IN',
    name: 'Sindhi',
    nativeName: 'سنڌي',
    native: 'سنڌي',
    script: 'Arabic / Devanagari',
    region: 'Sindhi Heritage & Western India',
    keyChar: 'س',
    color: '#b45309',
  },
  {
    code: 'ta-IN',
    ttsCode: 'ta-IN',
    name: 'Tamil',
    nativeName: 'தமிழ்',
    native: 'தமிழ்',
    script: 'Tamil',
    region: 'Tamil Nadu & South India',
    keyChar: 'அ',
    color: '#047857',
  },
  {
    code: 'te-IN',
    ttsCode: 'te-IN',
    name: 'Telugu',
    nativeName: 'తెలుగు',
    native: 'తెలుగు',
    script: 'Telugu',
    region: 'Andhra Pradesh & Telangana',
    keyChar: 'అ',
    color: '#4338ca',
  },
  {
    code: 'ur-IN',
    ttsCode: 'ur-IN',
    name: 'Urdu',
    nativeName: 'اردو',
    native: 'اردو',
    script: 'Perso-Arabic',
    region: 'Pan-India & Deccan',
    keyChar: 'ا',
    color: '#15803d',
  },
  // Additional Regional Languages with standard BCP 47 codes
  ...ADDITIONAL_LANGUAGES.filter((l) => l.code !== 'hi-IN'),
];
